### ISSUE TITLE
npm run pdfでエラー

### ISSUE THREAD

**Issue by bati668** [TechBooster/C89-FirstStepReVIEW-v2#57]
npm run pdf コマンドを実行したら以下のerrorが出ました。
rubyなどを初めて触るので、どこにエラーがあるのかわからず、ご教授いただきたいです。

コマンド実行手順
```
rubyをinstall
rbenvをinstall
nmpをinstall
Node.jsをinstall
graphvizをinstall

gem install bundler
git clone git@github.com:TechBooster/C89-FirstStepReVIEW-v2.git
cd C89-FirstStepReVIEW-v2
npm install
npm run pdf
```

```
 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'pdf' ]
2 info using npm@5.6.0
3 info using node@v9.7.0
4 verbose run-script [ 'prepdf', 'pdf', 'postpdf' ]
5 info lifecycle c89-firststepreview-v2@0.0.1~prepdf: c89-firststepreview-v2@0.0.1
6 info lifecycle c89-firststepreview-v2@0.0.1~pdf: c89-firststepreview-v2@0.0.1
7 verbose lifecycle c89-firststepreview-v2@0.0.1~pdf: unsafe-perm in lifecycle true
8 verbose lifecycle c89-firststepreview-v2@0.0.1~pdf: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/chibahiroshi/Desktop/C89-FirstStepReVIEW-v2/node_modules/.bin:/Users/chibahiroshi/anaconda3/bin:/Users/chibahiroshi/.kiex/elixirs/elixir-1.3.4/bin:/Users/chibahiroshi/.kiex/bin:/Users/chibahiroshi/.rvm/gems/ruby-2.4.0/bin:/Users/chibahiroshi/.rvm/gems/ruby-2.4.0@global/bin:/Users/chibahiroshi/.rvm/rubies/ruby-2.4.0/bin:/path/to/anaconda/bin:/Users/chibahiroshi/.nodebrew/current/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/chibahiroshi/.rvm/bin
9 verbose lifecycle c89-firststepreview-v2@0.0.1~pdf: CWD: /Users/chibahiroshi/Desktop/C89-FirstStepReVIEW-v2
10 silly lifecycle c89-firststepreview-v2@0.0.1~pdf: Args: [ '-c', 'grunt pdf' ]
11 silly lifecycle c89-firststepreview-v2@0.0.1~pdf: Returned: code: 6  signal: null
12 info lifecycle c89-firststepreview-v2@0.0.1~pdf: Failed to exec pdf script
13 verbose stack Error: c89-firststepreview-v2@0.0.1 pdf: `grunt pdf`
13 verbose stack Exit status 6
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:127:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:127:13)
13 verbose stack     at maybeClose (internal/child_process.js:936:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid c89-firststepreview-v2@0.0.1
15 verbose cwd /Users/chibahiroshi/Desktop/C89-FirstStepReVIEW-v2
16 verbose Darwin 16.7.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "pdf"
18 verbose node v9.7.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 6
22 error c89-firststepreview-v2@0.0.1 pdf: `grunt pdf`
22 error Exit status 6
23 error Failed at the c89-firststepreview-v2@0.0.1 pdf script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 6, true ]

```

**Comment by mstssk** [comment]
@bati668 
`npm run html` など他のコマンドは成功しますか？
`npm run pdf` だけが失敗するのであれば、TeXのセットアップがうまく行っていないのかもしれません（Re:VIEWはPDFを作るためにTeXを使用します）。

**Comment by bati668** [comment]
あ、すみません。TeXをダウンロードしてませんでした。
TeXをダウンロードしたら、うまく行きました！
ありがとうございます。
@mstssk

**Comment by mhidaka** [comment]
Thank you for your work @mstssk
Issueは閉じますね
