### ISSUE TITLE
build-in-docker.sh がエラーになる

### ISSUE THREAD

**Issue by miyajan** [TechBooster/C89-FirstStepReVIEW-v2#61]
最新の `vvakame/review` イメージだと、bundler のバージョンが `Gemfile.lock` に BUNDLED WITH で書かれているバージョンの `1.15.3` と合わずにエラーになるようです。

```bash
$ ./build-in-docker.sh 
（省略）
+ bundle install --path vendor/bundle
Traceback (most recent call last):
	2: from /usr/local/bin/bundle:23:in `<main>'
	1: from /usr/lib/ruby/2.5.0/rubygems.rb:303:in `activate_bin_path'
/usr/lib/ruby/2.5.0/rubygems.rb:284:in `find_spec_for_exe': Could not find 'bundler' (1.15.3) required by your /book/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:1.15.3`

> c89-firststepreview-v2@0.0.1 pdf /book
> grunt pdf

Running "clean:review" (clean) task
>> 0 paths cleaned.

Running "clean:publish" (clean) task
>> 0 paths cleaned.

Running "shell:preprocess" (shell) task
/usr/lib/ruby/2.5.0/rubygems.rb:284:in `find_spec_for_exe': Could not find 'bundler' (1.15.3) required by your /book/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:1.15.3`
	from /usr/lib/ruby/2.5.0/rubygems.rb:303:in `activate_bin_path'
	from /usr/local/bin/bundle:23:in `<main>'
Warning: Command failed: bundle exec review-preproc -r --tabwidth=2 *.re
/usr/lib/ruby/2.5.0/rubygems.rb:284:in `find_spec_for_exe': Could not find 'bundler' (1.15.3) required by your /book/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:1.15.3`
	from /usr/lib/ruby/2.5.0/rubygems.rb:303:in `activate_bin_path'
	from /usr/local/bin/bundle:23:in `<main>'
 Use --force to continue.

Aborted due to warnings.
npm ERR! code ELIFECYCLE
npm ERR! errno 6
npm ERR! c89-firststepreview-v2@0.0.1 pdf: `grunt pdf`
npm ERR! Exit status 6
npm ERR! 
npm ERR! Failed at the c89-firststepreview-v2@0.0.1 pdf script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-12-16T13_02_41_051Z-debug.log
```

回避策として、`Gemfile.lock` の BUNDLED WITH を `2.0.3` にすればビルドできることを確認しました。ただ、自分が ruby に詳しくないためこの修正が適切なのかよくわからず、すみませんがご対応お願いいたします。

素晴らしい書籍の公開ありがとうございます！

**Comment by mhidaka** [comment]
ご報告ありがとうございます。確認しますね

**Comment by vvakame** [comment]
docker imageのhashを固定するのがよさそうですね…。
このリポジトリはメンテナンスモードとして、雛形の利用は https://github.com/TechBooster/ReVIEW-Template を促すのがよさそうです。
